workflows:
  default-workflow:
    name: Android Debug Build
    environment:
      flutter: 3.10.6
      java: 11

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
